### ISSUE TITLE
Auto Hibernation stopped working in Google Pixel 6 Pro after Android 12 March Update

### ISSUE THREAD

**Issue by swarnaditya** [greenify/greenify.github.io#13]

**Comment by swarnaditya** [comment]
Oasis had acknowledged the issue last week in twitter. Attaching twitter conversation url just for reference with a screen recording and I think it would be helpful for all.  
 https://twitter.com/oasisfeng/status/1525034078604787713?t=07MfC2Gg5GdUNwQNrNJRIg&s=19
 
I am raising this issue here for a tracking purpose.

**Comment by oasisfeng** [comment]
The cause is still unclear, as accessibility service is no longer working as before.

I'm working on a solution based on [Shizuku](https://github.com/RikkaApps/Shizuku/) for non-rooted devices, ditching accessibility service for good.

**Comment by oasisfeng** [comment]
A new DEV version with [Shizuku](https://play.google.com/store/apps/details?id=moe.shizuku.privileged.api) support to overcome the compatibility issue caused by March update.
https://www.dropbox.com/sh/mspso6yvv1wbvju/p0AK2l3vmZ?lst=

Without root, Shizuku can be activated via "Wireless Debugging" (once every device reboot), grant privilege to Greenify in Shizuku app, then Greenify can work as smooth as in root mode.

**Comment by swarnaditya** [comment]
Fixed with Android 13 Beta update.

**Comment by swarnaditya** [comment]
Not able to add newly installed applications into Grennify. When I am clicking the + button on top right Grennify automatically closing itself.

Android version : 13 Beta
Phone : Pixel 6 Pro
Greenify version: 4.7.5
